import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * A registry is a folder with one file per entry (a screen, a work mode, a monster body, an AI route,
 * a bot command). This writes the folder's index so adding an entry is one new file and no list edit.
 *
 *   tsx tools/scripts/generate-index.ts <folder>...           write each folder's index
 *   tsx tools/scripts/generate-index.ts --check <folder>...   fail when an index is out of date
 */
export const generatedIndexName = 'index.generated.ts';

const header = '// Generated by tools/scripts/generate-index.ts. Never edit by hand.\n';
const moduleFile = /\.tsx?$/;
const notAnEntry = /^index\.|\.(test|spec)\.tsx?$|\.d\.ts$/;

/** Entry module names of a registry folder, without extension, in a stable order. */
export function registryModules(folder: string): string[] {
  return readdirSync(folder, { withFileTypes: true })
    .filter(
      (entry) => entry.isFile() && moduleFile.test(entry.name) && !notAnEntry.test(entry.name),
    )
    .map((entry) => entry.name.replace(moduleFile, ''))
    .sort();
}

export function renderIndex(modules: readonly string[]): string {
  if (modules.length === 0) return `${header}export {};\n`;
  return header + modules.map((name) => `export * from './${name}';\n`).join('');
}

/** True when the folder's index already matches its files. */
export function indexIsCurrent(folder: string): boolean {
  const file = path.join(folder, generatedIndexName);
  return existsSync(file) && readFileSync(file, 'utf8') === renderIndex(registryModules(folder));
}

export function writeIndex(folder: string): void {
  writeFileSync(path.join(folder, generatedIndexName), renderIndex(registryModules(folder)));
}

function main(args: readonly string[]): void {
  const check = args.includes('--check');
  const folders = args.filter((arg) => arg !== '--check');
  if (folders.length === 0) {
    console.error('Usage: generate-index.ts [--check] <registry folder>...');
    process.exitCode = 1;
    return;
  }
  for (const folder of folders) {
    if (!check) writeIndex(folder);
    else if (!indexIsCurrent(folder)) {
      console.error(`${path.join(folder, generatedIndexName)} is out of date; run generate-index.`);
      process.exitCode = 1;
    }
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main(process.argv.slice(2));
