import { enContextWords } from './en-context';
import { enTopicContextWords } from './en-context-topics';
import type { VoiceGuide } from './types';

/** The English word lists: what the prompt forbids and what the checker looks for. */
export const enWords: Pick<
  VoiceGuide,
  'bannedWords' | 'contextWords' | 'offLimits' | 'offLimitsNote' | 'userWorth' | 'missedDays'
> = {
  contextWords: [...enContextWords, ...enTopicContextWords],
  bannedWords: [
    'laziness',
    'miss call*',
    'finally',
    "shouldn't",
    "should've",
    'overdue',
    'procrastinat*',
    'ashamed',
    'disappoint*',
    "still haven't",
    'still have not',
    'productive',
    'productivity',
    'discipline*',
    'willpower',
    'just do it',
    "you've got this",
    'you got this',
    'you can do it',
    'believe in you',
    'proud of you',
  ],
  offLimits: {
    politics: [
      'politic*',
      'election*',
      'prime minister',
      'parliament*',
      'congress',
      'senat*',
      'communis*',
      'democrat*',
      'republican*',
      'ballot*',
      'coup',
      'dictator*',
      'martial law',
      'referendum',
      'party meeting',
      'party cell',
      'mayor*',
      'filibuster*',
      'sovereign nation',
      'constitution',
      'manifesto',
    ],
    religion: [
      'god',
      'gods',
      'jesus',
      'christ',
      'allah',
      'buddha',
      'church*',
      'mosque*',
      'temple*',
      'synagogue*',
      'bible',
      'quran',
      'priest*',
      'pastor*',
      'nun',
      'nuns',
      'heaven',
      'religio*',
      'sermon*',
      'gospel',
      'amen',
    ],
    bodies: ['obese', 'chubby', 'calorie*', 'thirst trap*', 'sexy', 'nude'],
    harm: ['suicid*', 'funeral*', 'delete myself', 'hurt myself'],
    hardship: ['homeless*', 'beggar*', 'bankrupt*'],
  },
  offLimitsNote:
    "politics and governments, religion, anyone's body or looks, death or self-harm, poverty or homelessness, the user's worth, and days that went by. If the task itself touches one of these, write about Scootch and the furniture instead.",
  userWorth: [
    'your fault',
    'wrong with you',
    'why are you like this',
    "you're so",
    'you are so',
    "you're such",
    'you forgot',
    'you keep',
    'you still',
    'put this off',
    'put it off',
    'putting this off',
    'putting it off',
    'been avoiding',
    'you avoided',
    'even you',
    'worthless',
    'useless',
    'pathetic',
    'hopeless',
    'disaster',
    'loser',
    'good enough',
    'better than you',
    'everyone else',
    'be gentle with yourself',
    'doing your best',
    'future you',
    'beaten by',
    'forgot her',
    'forgot him',
    'is crying',
  ],
  missedDays: [
    'yesterday',
    'welcome back',
    'long time no see',
    'been a while',
    'where have you been',
    'where were you',
    "haven't seen you",
    'in a row',
    'showed up',
    'showing up',
    'came back',
    "you're back",
    'you are back',
  ],
};
