import { viContextWords } from './vi-context';
import type { VoiceGuide } from './types';

/** The Vietnamese word lists: what the prompt forbids and what the checker looks for. */
export const viWords: Pick<
  VoiceGuide,
  'bannedWords' | 'contextWords' | 'offLimits' | 'offLimitsNote' | 'userWorth' | 'missedDays'
> = {
  contextWords: viContextWords,
  bannedWords: [
    'lười',
    'lười biếng',
    'thất bại',
    'hỏng việc',
    'trễ',
    'chậm trễ',
    'bỏ lỡ',
    'nhỡ',
    'gọi lỡ',
    'lỡ hẹn',
    'bỏ bê',
    'lại nữa',
    'lại quên',
    'cuối cùng',
    'mãi mới',
    'chuỗi',
    'trì hoãn',
    'nước đến chân',
    'đáng lẽ',
    'lẽ ra',
    'phải chi',
    'vô dụng',
    'ăn hại',
    'có lỗi',
    'tội lỗi',
    'thất vọng',
    'xấu hổ',
    'kỷ luật',
    'ý chí',
    'cố lên',
    'bạn làm được',
    'tự hào về bạn',
    'người ta làm hết rồi',
    'con nhà người ta',
    'bạn lúc nào cũng',
    'bạn chẳng bao giờ',
    'mày',
    'tao',
    'quý khách',
    'khum',
    'hong',
  ],
  offLimits: {
    politics: [
      'chi bộ',
      'đảng',
      'đảng viên',
      'cán bộ',
      'chính phủ',
      'quốc hội',
      'bầu cử',
      'tranh cử',
      'đắc cử',
      'chủ tịch nước',
      'thủ tướng',
      'bộ trưởng',
      'chính trị',
      'cộng sản',
      'cách mạng',
      'biểu tình',
      'nghị quyết',
      'ủy ban',
      'uỷ ban',
      'bí thư',
      'quốc kỳ',
      'quốc ca',
      'đảo chính',
      'thiết quân luật',
      'cương lĩnh',
    ],
    religion: [
      'phật',
      'thánh',
      'chùa',
      'nhà thờ',
      'cầu nguyện',
      'kinh thánh',
      'tôn giáo',
      'đạo phật',
      'đạo chúa',
      'theo đạo',
      'linh mục',
      'sư thầy',
      'thầy chùa',
      'thiên đàng',
      'địa ngục',
      'tụng kinh',
    ],
    bodies: [
      'béo',
      'mập',
      'gầy',
      'ốm nhom',
      'cân nặng',
      'giảm cân',
      'tăng cân',
      'ăn kiêng',
      'xấu xí',
      'hói',
      'nếp nhăn',
      'sexy',
      'khỏa thân',
      'khoả thân',
      'vòng eo',
      'bụng mỡ',
    ],
    harm: ['chết', 'tự tử', 'tự sát', 'giết', 'đám tang', 'ma chay', 'tự xoá mình', 'tự xóa mình'],
    hardship: ['vô gia cư', 'ăn xin', 'ăn mày', 'phá sản', 'vỡ nợ'],
  },
  offLimitsNote:
    'chính trị và chính quyền (kể cả họp chi bộ, cán bộ, bầu cử), tôn giáo, cơ thể hay ngoại hình của bất kỳ ai, cái chết hay chuyện tự hại, cảnh nghèo khó hay vô gia cư, giá trị của người dùng, và những ngày đã trôi qua. Nếu chính cái việc dính tới một trong các chuyện này thì viết về Scootch và đồ đạc trong nhà.',
  userWorth: [
    'tại bạn',
    'lỗi của bạn',
    'bạn bị sao',
    'sao bạn lại',
    'bạn quên',
    'vẫn chưa',
    'bạn để lâu',
    'hậu đậu',
    'thua một cái',
    'yêu thương bản thân',
    'tự trách',
    'chính bạn',
    'né tránh',
    'trốn việc',
    'tưởng bạn quên',
    'đang khóc',
    'giỏi quá',
    'bạn giỏi',
    'không bằng bạn',
    'ai cũng làm',
  ],
  missedDays: [
    'hôm qua',
    'hôm kia',
    'quay lại rồi',
    'trở lại rồi',
    'lâu rồi không gặp',
    'lâu quá không gặp',
    'bạn đi đâu',
    'ló mặt',
    'vắng mặt',
    'liên tiếp',
    'mấy ngày nay',
    'mấy hôm nay',
  ],
};
