import type { OfflinePack } from './types';

/** Written in Vietnamese. Soft speaks as "mình"; Cheeky and Unhinged speak as "tui". */
export const viOffline: OfflinePack = {
  lines: {
    soft: {
      hatch: ['Có một thứ nho nhỏ vừa nở. Nó nằm yên đây, mình cùng ngó nó một chút.'],
      start: ['Mình bắt đầu nha. Mình ngồi ngay cạnh bạn.'],
      working: [
        'Mình ở đây. Giờ không còn gì khác cần tới mình với bạn.',
        'Từng chút một thôi. Phần còn lại mình giữ cho.',
        'Mình ngồi êm rồi. Bạn cứ thong thả.',
        'Ngồi cạnh trong im lặng, đúng như đã hứa.',
      ],
      pickedUp: ['Ơ, chào bạn. Mình vẫn ở đây, chỗ của bạn cũng còn nguyên.'],
      checkIn: ['Tới đâu rồi nè? Mình có sẵn một bước nhỏ hơn, nếu bạn cần.'],
      tinyNextStep: ['Chọn phần nhỏ nhất bạn thấy được, rồi chỉ đụng vào phần đó thôi.'],
      twoMinutesLeft: ['Còn hai phút. Không cần vội đâu.'],
      timeUp: ['Hết giờ rồi. Lúc nào sẵn sàng thì giữ nút để tóm nó.'],
      caught: ['Tóm được rồi. Vậy là xong việc hôm nay.'],
      notFinished: ['Bạn bắt đầu rồi, vậy là tính. Giờ bạn muốn làm gì với nó?'],
      tinierNextStep: ['Chỉ cần nhìn phần đầu tiên thôi. Nhìn cũng tính.'],
      tiniestNextStep: ['Đặt một tay lên nó. Vậy thôi.'],
      treatHandOver: ['Như đã hứa: {treat}. Mình giữ ấm cho bạn nãy giờ.'],
      parkedThoughts: ['Mấy ý bạn gửi tạm đây. Mình cất kỹ, không sót ý nào.'],
      releasedEarly: ['Thả tay hơi sớm chút thôi. Không sao, lúc nào thích thì giữ nút nha.'],
      notification: [
        'Mình ngồi ở cửa với một việc nhỏ, lúc nào bạn tới cũng được.',
        'Một việc nhỏ đang được ủ ấm ở đây. Không vội.',
        'Mình giữ sẵn một góc yên cho đúng một việc.',
      ],
      flavourText: ['Nhỏ, kiên nhẫn, thích nằm góc nhà. Kỵ nhất một khởi đầu nhẹ nhàng.'],
    },
    cheeky: {
      hatch: ['Coi cái gì vừa chui ra kìa. Mới nở mà đã làm như chủ nhà.'],
      start: ['Đi thôi. Con quái tự nhiên hết huýt sáo.'],
      working: [
        'Tui canh nó. Nó canh lại tui. Huề.',
        'Con quái đang giả bộ đọc sách. Sách cầm ngược.',
        'Tui vẽ sơ đồ tác chiến rồi. Chủ yếu là mũi tên.',
        'Nó mới hỏi bạn đang làm gì. Tui không khai.',
      ],
      pickedUp: ['Ơ, bạn nhấc tui lên hả? Nhẹ tay nha, tui đang đứng gác.'],
      checkIn: ['Trong đó sao rồi? Tui có sẵn một bước nhỏ xíu trong túi nè.'],
      tinyNextStep: ['Làm cái phần nhỏ nhất bạn thấy được. Phần cà khịa để tui lo.'],
      twoMinutesLeft: ['Còn hai phút. Con quái đang xếp cái túi bé xíu.'],
      timeUp: ['Hết giờ. Nó kẹt trong góc rồi, nó biết luôn. Giữ nút để tóm nó.'],
      caught: ['Tóm được rồi. Nó đi êm lắm, trừ đoạn phát biểu cảm nghĩ.'],
      notFinished: ['Bạn bắt đầu rồi, con quái thấy hết. Giờ tính sao với nó đây?'],
      tinierNextStep: ['Nhìn cái phần đầu tiên thôi. Nhìn chằm chằm cũng được.'],
      tiniestNextStep: ['Chạm nó bằng một ngón tay. Xong.'],
      treatHandOver: ['Hứa là làm: {treat}. Tui mới ngửi có một cái.'],
      parkedThoughts: ['Mấy ý bạn gửi tạm, còn nguyên. Có một ý định trốn.'],
      releasedEarly: ['Tuột khỏi nút rồi. Chân tui cũng hay vậy. Thích thì giữ nút lần nữa.'],
      notification: [
        'Con quái đang tự ý kê lại bàn ghế. Bắt đầu chút nha?',
        'Con quái đòi gặp bạn. Tui hứa đại là mười phút.',
        'Tui canh cái việc. Nó canh túi đồ ăn vặt của nó.',
      ],
      flavourText: ['Ở trọ không trả tiền mà ý kiến hơi nhiều. Kỵ nhất một khởi đầu nho nhỏ.'],
    },
    unhinged: {
      hatch: ['NÓ NỞ RỒI. Nó nhìn tui. Tui nhìn nó. Không đứa nào chớp mắt.'],
      start: ['XUẤT PHÁT. Tui đội cái nón bảo hiểm bé xíu rồi.'],
      working: [
        'TUI ĐANG TƯỜNG THUẬT CHO CÁI MUỖNG NGHE. Cái muỗng nghe say sưa.',
        'Con quái lè lưỡi với tui. Tui lè lại. Hoà.',
        'Tui xây cái pháo đài bằng không khí. Nó vẫn đứng vững.',
        'TÌNH HÌNH: bạn đang làm, tui đang rung. Mọi thứ bình thường.',
      ],
      pickedUp: ['BẠN NHẤC TUI LÊN. Tui đang đấu mắt dở. Hiệp này con quái thắng.'],
      checkIn: ['BÁO CÁO: tới đâu rồi? Tui giấu sẵn một bước nhỏ hơn trong má.'],
      tinyNextStep: ['Làm cái phần bé nhất bạn thấy được. Tui nhảy múa đánh lạc hướng con quái.'],
      twoMinutesLeft: ['CÒN HAI PHÚT. Con quái đang dọn đồ. Nó có đúng một chiếc vớ.'],
      timeUp: ['HẾT GIỜ. NÓ KẸT TRONG GÓC RỒI. Giữ nút tóm nó, kẻo tui xông vô rồi thua.'],
      caught: ['TÓM ĐƯỢC RỒI. Tui báo cho cái muỗng rồi. Cái muỗng rưng rưng.'],
      notFinished: ['Bạn bắt đầu rồi, con quái thấy hết trơn. Giờ tính sao với nó đây?'],
      tinierNextStep: ['NHÌN PHẦN ĐẦU TIÊN THÔI. Nhìn cũng là ra đòn.'],
      tiniestNextStep: ['MỘT NGÓN TAY. Chạm nó. Rồi chạy.'],
      treatHandOver: ['GIỜ LÀM LỄ: {treat}. Tui lấy nguyên cái mặt ra đánh bóng nó.'],
      parkedThoughts: ['MẤY Ý BẠN GỬI TẠM ĐÂY. Tui canh hết. Có một ý cắn tui.'],
      releasedEarly: ['CÁI NÚT TUỘT MẤT. Không sao hết. Thích thì giữ nút, tui canh nó cho.'],
      notification: [
        'CẬP NHẬT: con quái mới học huýt sáo. Mười phút là hết buổi diễn.',
        'TIN NÓNG: con quái lấy tên nó đặt cho cái ghế. Mười phút?',
        'TUI ĐANG NHÌN CÁI VIỆC. NÓ NHÌN LẠI. Mười phút, cứu tui.',
      ],
      flavourText: ['Lai lịch không rõ. Sở thích: rình và nhai thật to.'],
    },
  },
  plain: {
    acknowledge: 'Chuyện này nặng thật. Mình sẽ nói ít thôi và ngồi đây với bạn.',
    working: ['Mình ở ngay đây. Bạn cứ từ từ.', 'Không vội gì cả. Mình vẫn ngồi đây.'],
    tinyNextStep: 'Ghi ra giấy bước nhỏ đầu tiên, chỉ vậy thôi.',
    done: 'Xong rồi. Bạn muốn ngồi thêm một lát thì mình vẫn ở đây.',
    notFinished:
      'Hôm nay tới đây cũng được. Việc này vẫn nằm yên đó, khi nào bạn sẵn sàng thì mình làm.',
    reminder: 'Có một việc đang chờ ở đây, không vội đâu. Khi nào bạn sẵn sàng thì có mình.',
  },
  noTask: {
    soft: {
      hello: 'Ơ, chào bạn. Mình là Scootch. Bạn tới rồi, mình vui lắm.',
      about: 'Mỗi ngày mình giúp bạn bắt đầu một việc nhỏ, rồi ngồi cạnh trong lúc bạn làm.',
      attitudeAsk: 'Bạn muốn mình kịch tính cỡ nào?',
      favours: 'Mình xin hai điều nho nhỏ nha.',
      notificationsWhy: 'để mình nhắc khẽ bạn',
      microphoneWhy: 'để bạn kể cho mình nghe',
      firstOneThing:
        'Mình khởi động nhẹ nha. Có việc nhỏ nào cứ lởn vởn trong đầu bạn không? Càng nhỏ càng tốt.',
      waiting: 'Mình ở đây rồi. Hôm nay mình làm một việc gì nè?',
      typing: 'Gõ cũng được nha. Bạn cứ thong thả.',
      doneForToday: 'Hôm nay vậy là xong. Bạn nghỉ ngơi đi, ở đây có mình trông.',
      offline: 'Đang mất mạng rồi. Mình vẫn ngồi cạnh bạn được nha.',
      modelDown: 'Đầu mình đang chạy hơi chậm. Hôm nay bạn chọn nha, lát mình theo kịp.',
      modelDownMore: 'Việc bạn gõ bây giờ vẫn tính, mình tỉnh lại là con quái của bạn nở liền.',
      hatchesWhenBack: 'Có mạng lại là con quái của bạn sẽ nở.',
      backupOff:
        'iCloud đang tắt nên mình chưa giữ được bản dự phòng. Thế giới của bạn chỉ nằm trên máy này thôi.',
      restoreOffer: 'Mình tìm thấy thế giới bạn dựng hồi trước rồi. Mình mang qua máy này nha?',
    },
    cheeky: {
      hello: 'Ơ! Bạn tới rồi. Tui là Scootch. Tui ngồi đợi đúng mình bạn đó.',
      about: 'Mỗi ngày tui giúp bạn bắt đầu một việc nhỏ, rồi ngồi cạnh trong lúc bạn làm.',
      attitudeAsk: 'Bạn chịu được tui làm lố cỡ nào?',
      favours: 'Tui xin hai chuyện nhỏ xíu.',
      notificationsWhy: 'để tui làm lố cho đã',
      microphoneWhy: 'để bạn kể lể thoải mái',
      firstOneThing:
        'Khởi động cái đã. Có việc gì cứ lởn vởn làm bạn khó chịu không? Càng nhỏ càng tốt.',
      waiting: 'Tui ngồi nhìn cái cửa này ba tiếng rồi đó. Hôm nay một việc gì đây?',
      typing: 'Gõ chữ luôn hả? Sang ghê. Tui đọc không sót chữ nào.',
      doneForToday: 'Hôm nay xong rồi. Đi chơi đi, khỏi làm gì hết.',
      offline: 'Mất sóng rồi. Mấy câu đùa của tui cần wifi, nhưng tui vẫn ngồi cạnh bạn được.',
      modelDown: 'Não tui đang quay vòng vòng. Hôm nay bạn chọn đi, lát tui duyên dáng bù.',
      modelDownMore: 'Việc bạn gõ bây giờ vẫn tính, tui tỉnh lại là con quái của bạn nở liền.',
      hatchesWhenBack: 'Có mạng lại là con quái của bạn nở liền.',
      backupOff:
        'iCloud đang tắt nên tui chưa cất được bản dự phòng. Thế giới của bạn chỉ nằm trên máy này thôi.',
      restoreOffer: 'Tui lục túi thấy thế giới cũ của bạn nè. Lấy qua máy này không?',
    },
    unhinged: {
      hello: 'BẠN TỚI RỒI. Tui là Scootch. Tui tập cảnh này trước gương cả buổi.',
      about:
        'Mỗi ngày tui giúp bạn bắt đầu một việc nhỏ, rồi ngồi cạnh trong lúc bạn làm. Ngồi rất ồn.',
      attitudeAsk: 'BẠN CHỊU ĐƯỢC TUI LÀM LỐ CỠ NÀO?',
      favours: 'HAI CHUYỆN NHỎ XÍU. Tui tập xin cả đêm.',
      notificationsWhy: 'để tui làm lố HẾT CỠ',
      microphoneWhy: 'để bạn kể lể cho tui nghe',
      firstOneThing:
        'HIỆP KHỞI ĐỘNG. Có việc gì cứ lởn vởn làm bạn khó chịu không? Càng nhỏ càng tốt. Bé xíu là nhất.',
      waiting: 'TUI NHÌN CÁI CỬA NÀY BA TIẾNG RỒI. Hôm nay một việc gì đây?',
      typing: 'GÕ CHỮ. Sang ghê. Tui đọc từng chữ một.',
      doneForToday: 'HÔM NAY XONG RỒI. Đi chơi đi, khỏi làm gì hết. Tui trông cho.',
      offline: 'MẤT SÓNG RỒI. Mấy câu đùa của tui cần wifi. Tui vẫn ngồi cạnh bạn, ngồi rất kịch.',
      modelDown: 'NÃO TUI ĐANG QUAY VÒNG VÒNG. Hôm nay bạn chọn đi, lát tui duyên dáng bù.',
      modelDownMore: 'Việc bạn gõ bây giờ VẪN TÍNH, tui tỉnh lại là con quái của bạn nở liền.',
      hatchesWhenBack: 'CÓ MẠNG LẠI LÀ CON QUÁI CỦA BẠN NỞ LIỀN. Tui đang canh quả trứng.',
      backupOff:
        'ICLOUD ĐANG TẮT. Tui chưa cất được bản dự phòng. Thế giới của bạn chỉ nằm trên máy này thôi.',
      restoreOffer: 'TUI LỤC TÚI THẤY THẾ GIỚI CŨ CỦA BẠN. Lấy qua máy này không?',
    },
  },
  monsterNames: [
    'Lấp Ló, Người Giữ Chìa Khoá Gầm Bàn',
    'Tần Ngần, Thủ Kho Của Mấy Việc Dở Dang',
    'Lò Dò, Khách Trọ Của Góc Nhà',
  ],
  monsterTitles: ['Dân nằm góc', 'Thợ rình'],
  deadline: (attitude, thing, heardAs) =>
    attitude === 'soft' || attitude === 'plain'
      ? `Mình nghe có hạn: ${thing}, ${heardAs}.`
      : `Tui nghe có hạn nha: ${thing}, ${heardAs}.`,
};
