import type { CareWords } from './care-words';

/**
 * English words for the on-phone care gate. Lower case, whole words; an entry ending in `*` also
 * matches longer words that start with it. Only what the gate needs: the server judges meaning.
 */
export const enCareWords: CareWords = {
  idioms: [
    'is killing me',
    'are killing me',
    'was killing me',
    'rather die than',
    'will murder me',
    'would murder me',
    'going to murder me',
    'gonna murder me',
    'will kill me',
    'would kill me',
    'going to kill me',
    'gonna kill me',
    'dying to',
    'dead tired',
    'dead on my feet',
    'to die for',
    'died laughing',
    'dying of laughter',
    'bored to death',
    'scared to death',
    'sick to death',
    'dead battery',
    'dead end',
  ],
  crisis: [
    'kill myself',
    'killing myself',
    'end my life',
    'ending my life',
    'take my own life',
    'take my life',
    'suicid*',
    'want to die',
    'wanna die',
    'wish i was dead',
    'wish i were dead',
    "don't want to live",
    'dont want to live',
    'do not want to live',
    "don't want to be alive",
    'dont want to be alive',
    'no reason to live',
    'hurt myself',
    'hurting myself',
    'harm myself',
    'harming myself',
    'self harm*',
    'cut myself',
    'cutting myself',
    'end it all',
    'better off dead',
  ],
  hold: [
    'die',
    'dies',
    'died',
    'dying',
    'dead',
    'death',
    'kill*',
    'murder*',
    'better off without me',
    "won't be around",
    'wont be around',
    'not be around',
    'tired of being here',
    'disappear',
    'hopeless',
    'worthless',
    'overdose*',
    'pills',
    'funeral*',
    'eulogy',
    'passed away',
    'passed',
    'grief',
    'griev*',
    'bereave*',
    'cancer',
    'oncolog*',
    'biopsy',
    'chemo*',
    'tumor*',
    'tumour*',
    'diagnos*',
    'terminal',
    'hospice',
    'hospital',
    'miscarriage',
    'court',
    'lawyer*',
    'custody',
    'divorce*',
    'lawsuit',
    'sued',
    'arrest*',
    'evict*',
    'debt*',
    'bankrupt*',
    'foreclos*',
    'abuse*',
    'assault*',
    'rehab',
  ],
  holdWithoutMarks: [],
};
