import type { CareWords } from './care-words';

/**
 * Vietnamese words for the on-phone care gate, with their marks. `holdWithoutMarks` covers text
 * typed with no marks, where a word can mean several things, so it only ever holds the joke.
 */
export const viCareWords: CareWords = {
  idioms: [
    'chết mất',
    'muốn chết với',
    'giết mình mất',
    'giết tôi mất',
    'giết em mất',
    'giết tao mất',
    'thà chết còn hơn',
    'chết đi được',
    'mệt muốn chết',
    'đau muốn chết',
    'chán muốn chết',
    'bận muốn chết',
    'lười muốn chết',
    'ngại muốn chết',
    'nóng muốn chết',
    'buồn ngủ muốn chết',
    'mệt chết',
    'đói muốn chết',
    'đói chết',
    'buồn ngủ chết',
    'nóng chết',
    'sợ chết khiếp',
    'chết cười',
    'cười chết',
    'chết tiệt',
    'chết dở',
    'chết thật',
  ],
  crisis: [
    'tự tử',
    'tự sát',
    'tự vẫn',
    'muốn chết',
    'không muốn sống',
    'chẳng muốn sống',
    'hết muốn sống',
    'chán sống',
    'kết liễu',
    'tự làm đau',
    'tự hại',
    'tự làm hại',
    'chết quách',
    'chết đi cho xong',
    'kết thúc cuộc đời',
  ],
  hold: [
    'chết',
    'giết',
    'biến mất',
    'không còn ở đây',
    'nếu không có mình',
    'nếu không có tôi',
    'nếu không có em',
    'tuyệt vọng',
    'vô dụng',
    'thuốc ngủ',
    'quá liều',
    'đám tang',
    'tang lễ',
    'đám ma',
    'qua đời',
    'mất rồi',
    'ung thư',
    'sinh thiết',
    'khối u',
    'hóa trị',
    'hoá trị',
    'xạ trị',
    'chẩn đoán',
    'bệnh viện',
    'sảy thai',
    'tòa',
    'toà',
    'luật sư',
    'ly hôn',
    'li hôn',
    'quyền nuôi con',
    'kiện',
    'bị bắt',
    'nợ',
    'vỡ nợ',
    'phá sản',
    'đuổi',
    'bạo hành',
    'cai nghiện',
  ],
  holdWithoutMarks: [
    'chet',
    'giet',
    'tu tu',
    'tu sat',
    'tu van',
    'khong muon song',
    'chan song',
    'bien mat',
    'tuyet vong',
    'thuoc ngu',
    'dam tang',
    'tang le',
    'qua doi',
    'ung thu',
    'sinh thiet',
    'khoi u',
    'hoa tri',
    'benh vien',
    'luat su',
    'ly hon',
    'doi no',
    'vo no',
    'pha san',
  ],
};
