/** The Get and Help pages, in Vietnamese. */
export const helpVi = {
  get: {
    title: 'Tải Scootch',
    description: 'Scootch có trên iPhone. Đưa camera vô mã, hoặc bấm nút trên điện thoại của bạn.',
    eyebrow: 'Tải Scootch',
    words: ['Con', 'quái', 'của', 'bạn', 'đang', 'chờ.'],
    phoneBody: 'Miễn phí trên iPhone. Con nào bạn ấp ở đây cũng đi theo được.',
    deskBody:
      'Đang dùng laptop? Đưa camera iPhone vô mã này. Nó mở trang này trên điện thoại, và App Store chỉ cách một chạm.',
    soonBody: 'Scootch chưa ra mắt. Để lại email, tới ngày ra mắt tui báo bạn.',
    store: 'Tải trên App Store',
    qrLabel: 'Mã QR mở trang này trên điện thoại của bạn',
    qrCaption: 'Đưa camera iPhone vô đây',
    androidEyebrow: 'Android',
    androidTitle: 'Chưa có trên Android.',
    pressEyebrow: 'Tài liệu báo chí',
    pressTitle: 'Bạn đang viết về Scootch?',
  },
  help: {
    title: 'Trợ giúp · Scootch',
    description:
      'Câu hỏi được trả lời thẳng, đường dây hỗ trợ, Scootch là gì và không là gì, và quyền riêng tư nói gọn.',
    address: 'scootch.app/vi/help',
    words: ['Tui', 'giúp', 'được', 'gì?'],
    searchLabel: 'Tìm trong các câu hỏi',
    searchPlaceholder: 'Tìm: huỷ, mất mạng, ngồi bàn…',
    search: 'Tìm',
    oneAnswer: '1 câu trả lời',
    answers: '{count} câu trả lời',
    nav: [
      'Câu hỏi',
      'Đường dây hỗ trợ',
      'Scootch là gì và không là gì',
      'Quyền riêng tư, nói thẳng',
      'Viết cho tụi tui',
    ],
    questionsTitle: 'Những câu người ta thật sự hỏi',
    tags: [
      'Plus',
      'App',
      'Về Scootch',
      'Về Scootch',
      'Dữ liệu',
      'App',
      'App',
      'Ngồi bàn',
      'App',
      'Plus',
      'Plus',
      'App',
      'App',
      'Dữ liệu',
      'Chăm sóc',
    ],
    none: 'Tui tìm không ra. Viết cho tụi tui ở bên dưới nha.',
    helplinesTitle: 'Nếu mọi thứ đang rất khó khăn',
    helplinesBody:
      'Bạn xứng đáng có một con người thật, không phải một nhân vật hoạt hình. Các đường dây này miễn phí và kín đáo. Nếu bạn đang gặp nguy hiểm ngay lúc này, hãy gọi số khẩn cấp ở nơi bạn ở.',
    country: 'Quốc gia',
    allHelplines: 'Mọi quốc gia, kèm giờ hoạt động',
    isntTitle: 'Scootch là gì, và không là gì',
    is: 'Scootch là',
    isList: [
      'Một người bạn nhỏ, ngớ ngẩn, giúp bạn bắt đầu việc',
      'Một cách làm cho việc đáng sợ thấy nhỏ lại',
      'Sự hiện diện yên lặng trong lúc bạn làm',
      'Miễn phí, không có gì đếm ngày của bạn',
    ],
    isnt: 'Scootch không là',
    isntList: [
      'Chẩn đoán, điều trị hay cách chữa ADHD hoặc bất cứ điều gì khác',
      'Nhà trị liệu, người huấn luyện hay dịch vụ khủng hoảng',
      'Bảng điểm năng suất',
      'Thứ thay thế cho những người quan tâm tới bạn',
    ],
    privacyTitle: 'Quyền riêng tư, nói thẳng',
    privacy: [
      {
        tag: 'Giọng nói',
        title: 'Kể lể vẫn chỉ là kể lể',
        body: 'Giọng bạn được chuyển thành chữ và Scootch không bao giờ giữ âm thanh.',
      },
      {
        tag: 'Việc',
        title: 'Danh sách là của bạn',
        body: 'Không ai ở bàn thấy câu chữ của bạn, và không có gì công khai trừ khi bạn chia sẻ.',
      },
      {
        tag: 'Huấn luyện',
        title: 'Không bao giờ dùng để huấn luyện',
        body: 'Không có gì bạn nói hay gõ được dùng để huấn luyện mô hình.',
      },
      {
        tag: 'Rời đi',
        title: 'Mang theo hoặc xoá hết',
        body: 'Xuất mọi thứ, hoặc xoá mọi thứ, ngay trong app, bất cứ lúc nào.',
      },
    ],
    privacyLinks:
      'Bảng đầy đủ nằm ở trang {privacy}, và {terms} cũng được viết bằng lời lẽ rõ ràng như vậy.',
    privacyLink: 'quyền riêng tư',
    termsLink: 'điều khoản',
    contactTitle: 'Viết cho một con người',
    contactBody: 'Thư nào cũng có người đọc, và không ai bắt bạn giải thích.',
    contactEmail: 'help@scootch.app',
  },
} as const;
