import type { Loosen } from './en';
import type { homeEn } from './home-en';

/** The home page below the maker, section by section, in Vietnamese. */
export const homeVi = {
  hunt: {
    eyebrow: 'Cách dùng · cuộn để săn',
    headline: 'Từ “ôi thôi” tới bắt gọn trong mười phút.',
    steps: [
      {
        title: 'Kể lể chừng hai mươi giây',
        body: 'Thuế, mẹ, nha sĩ, nhà tắm. Nói ra hết đi.',
      },
      { title: 'Một việc nở ra', body: 'Mấy việc còn lại vô ngăn kéo. Hôm nay là Răng Hàm.' },
      {
        title: 'Cuộc săn',
        body: 'Scootch chạy, Răng Hàm teo lại. Nhìn thấy ngay trên màn hình khoá.',
      },
      {
        title: 'Bắt nó. Xong.',
        body: 'Nó là của bạn mãi mãi, trên một tấm thẻ nghiêng qua nghiêng lại được.',
      },
    ],
    task: 'Email cho nha sĩ',
    lines: [
      'Răng Hàm chưa biết chuyện gì sắp tới.',
      'Răng Hàm đang toát mồ hôi. Tiếp đi.',
      'Răng Hàm còn có một nửa. Ha.',
      'Răng Hàm giờ bằng hạt bụi.',
    ],
    park: 'Gửi tạm một ý',
    stuck: 'Tui bị kẹt',
    cardTop: 'Đã bắt · 10 phút · Số 0043',
    cardTitle: 'Bắt được rồi.',
    cardBody: 'Răng Hàm đang ngồi trên kệ, mặt xụ một đống. Làm tốt lắm.',
  },
  lurk: {
    eyebrow: 'Bọn rình rập',
    headline: 'Việc bị lơ thì cứ to dần.',
    body: 'Mỗi ngày một việc nằm chờ, con quái của nó lớn thêm một chút. Không chuỗi ngày, không chấm đỏ, không ai trách móc. Chỉ có một sinh vật rõ ràng là ở lì quá lâu. Mười phút là nó teo lại liền.',
    drag: 'Kéo để lơ nó lâu hơn',
    sliderLabel: 'Số ngày rình rập',
    scale: ['Hôm nay', 'Một tuần', 'Hai tuần'],
    stages: [
      'Ngày đầu. Nhỏ xíu, lễ phép. Gần như không thấy.',
      'Được vài ngày. Đang ổn định chỗ ở. Có ý kiến về cái bàn của bạn.',
      'Một tuần. Đã dọn đồ ra. Đang đọc thư của bạn.',
      'Ép sát vô mặt kính. Mười phút là nó teo lại liền.',
    ],
    lurking: 'Đang rình',
    day: 'Ngày {n}',
    unitOne: 'ngày',
    unitMany: 'ngày',
    task: 'Khai thuế',
  },
  surfaces: {
    eyebrow: 'Ngoài app',
    headline: 'Cuộc săn theo bạn khắp nơi.',
    body: 'Trên màn hình khoá, trong Dynamic Island và ở StandBy. Gửi tạm một ý hay xin giúp mà không cần mở khoá. Bắt đầu từ nút Tác vụ, Trung tâm điều khiển hoặc một widget, không phải mở app nào, không có gì để lạc vô.',
    date: 'Thứ Năm, 8 tháng 10',
    task: 'Email cho nha sĩ',
    line: 'Răng Hàm đang toát mồ hôi. Tiếp đi.',
    island: 'Dynamic Island · chạm thử',
    islandLabel: 'Xem kiểu Dynamic Island tiếp theo',
    atTable: '3 người ở bàn',
    caught: 'Bắt được rồi.',
    caughtLine: 'Răng Hàm đã lên kệ',
    widgetDay: 'Ngày 9',
    widgetTask: 'Khai thuế',
    shelf: 'Kệ',
    chips: ['Nút Tác vụ', 'Trung tâm điều khiển', 'StandBy', 'Widget', 'Dynamic Island'],
  },
  tables: {
    eyebrow: 'Ngồi chung bàn · có người làm cùng',
    headline: 'Không ai nói gì. Ai cũng đang làm việc của mình.',
    body: 'Ngồi cùng tối đa ba người bạn, ai làm việc nấy. Người khác chỉ thấy một hai chữ về việc bạn đang làm. Không chat, chỉ có sự hiện diện yên lặng và thỉnh thoảng một cái vẫy tay không tiếng.',
    bar: 'Tập trung · 4 người ở bàn · còn 18:40',
    wave: 'Vẫy tay không tiếng',
    waved: 'Đã vẫy',
    wavedBack: 'Dana vẫy lại rồi. Làm tiếp nha.',
    seats: ['Bạn · email', 'Dana · viết', 'Sam · giấy tờ', 'Linh · dọn dẹp'],
  },
  attitudes: {
    eyebrow: 'Chọn một thái độ',
    headline: 'Bọn quái sẽ nhắn cho bạn. Chọn mức độ hỗn đi.',
    body: 'Tin nào cũng được viết mới, về đúng việc của bạn. Lơ tụi nó thì tụi nó nhỏ tiếng dần, không bao giờ to hơn. Tới giờ yên tĩnh là con nào cũng đi ngủ.',
    pick: 'Thái độ',
    names: ['Nhẹ nhàng', 'Lém lỉnh', 'Mất kiểm soát'],
    senders: ['Răng Hàm', 'Rắn Hoá Đơn Chín Đầu', 'Scootch'],
    now: 'vừa xong',
    notes: [
      [
        'Chào. Tui ở đây nè. Không gấp, nhưng thứ Năm sắp tới rồi.',
        'Chín ngày bên nhau. Mười phút thôi là tui nhỏ xíu liền.',
        'Hôm nay xong bốn việc. Biên lai gửi kèm nha.',
      ],
      [
        'Tui dọn vô ở thứ Năm của bạn rồi. Có mang theo cái sofa.',
        'Ngày thứ chín. Tui bắt đầu trang trí nhà cửa rồi.',
        'Xong bốn việc. Biên lai gửi kèm, theo truyền thống.',
      ],
      [
        'Tui học lái xe rồi. Tui đang tới thứ Năm.',
        'NGÀY THỨ CHÍN. TUI CÓ LUẬT SƯ RỒI. ỔNG CŨNG LÀ MỘT TỜ HOÁ ĐƠN.',
        'BỐN. BỐN VIỆC. Tui in biên lai ra rồi đóng khung luôn.',
      ],
    ],
  },
  prices: {
    eyebrow: 'Miễn phí mãi mãi · hoặc Plus',
    headline: 'Biến nó thành của bạn, bằng chất liệu thật.',
    body: 'Trọn một ngày là miễn phí, mãi mãi. Plus thêm chút Scootch, và thẻ của bạn mặc được cả bảy chất liệu. Thử một cái bên dưới đi.',
    finishLabel: 'Chất liệu',
    finishes: ['Giấy', 'Ánh kim', 'Crôm', 'Thạch', 'Kính mờ', 'Nhung', 'Riso'],
    cardTop: 'Scootch',
    cardNumber: 'Số 0042',
    plans: [
      { name: 'Hằng tháng', price: '$5.99', detail: 'mỗi tháng' },
      { name: 'Hằng năm', price: '$39.99', detail: '7 ngày đầu miễn phí' },
      { name: 'Trọn đời', price: '$89.99', detail: 'một lần, mãi mãi' },
    ],
    freeHeadline: 'Miễn phí mãi mãi',
    free: [
      'Mỗi ngày tới mười việc',
      'Con quái nào bắt được cũng giữ mãi',
      'Ngồi bàn cùng bạn bè, và tự mở bàn hai chỗ',
      'Đủ cả ba thái độ',
      'Bài hát hằng tuần, và chia sẻ nó',
    ],
    plusHeadline: 'Plus thêm',
    plus: [
      'Mọi chất liệu thẻ',
      'Mỗi ngày tới hai mươi lăm việc',
      'Mở bàn tới bốn chỗ',
      'Cuốn sổ thẻ, và giữ mọi bản thu hằng tuần',
      'Widget cỡ đại và StandBy',
    ],
    reminder:
      'Tui sẽ nhắc bạn một ngày trước mỗi lần tính tiền. Huỷ trong hai chạm ở phần cài đặt Apple.',
    allAboutPlus: 'Tất cả về Plus',
  },
  share: {
    eyebrow: 'Làm ra để khoe',
    headline: 'Khoe mấy chiến thắng nhỏ xíu đi.',
    body: 'Một tấm story in riso khi bạn bắt được gì đó, một tờ biên lai những việc đã xong trong ngày, và một tấm poster cuối tháng. Cái nào cũng mặc chất liệu của bạn.',
    storyLabel: 'Một tấm story: Bắt rồi. Nằm trong hộp thư của tui 11 ngày. Giờ hết rồi.',
    storyStamp: 'Bắt rồi.',
    storyLine: 'Nằm trong hộp thư của tui 11 ngày. Giờ hết rồi.',
    receiptLabel: 'Biên lai trong ngày: xong bốn việc.',
    receiptTitle: 'Sổ việc xong · T5 08/10',
    receiptRows: [
      ['trả lời Sam', '09:12'],
      ['email nha sĩ', '09:41'],
      ['gấp đồ', '11:40'],
      ['khai thuế ★', '14:05'],
    ],
    receiptTotal: 'Quái đã bắt',
    receiptThanks: 'Cảm ơn bạn đã mua sắm tại chính cuộc đời mình',
    posterLabel: 'Poster của tháng: bắt được 42 con quái trong tháng Chín.',
    posterTitle: 'Tháng Chín',
    posterLine: 'con quái đã bắt.',
  },
  who: {
    eyebrow: 'Dành cho ai',
    headline: 'Cho những bộ não mà bắt đầu là phần khó nhất.',
    body: 'Cho người có ADHD, và bất kỳ ai mà danh sách việc cần làm cũng có danh sách việc cần làm riêng. Scootch chạy từ những chỗ bạn vốn đã chạm tới, nên không có thói quen mới nào phải giữ.',
    tiles: [
      {
        tag: 'Bắt đầu',
        title: 'Một cú nhấn, từ bất cứ đâu',
        body: 'Nút Tác vụ, một widget, Trung tâm điều khiển. Bạn đã chạy trước khi kịp chần chừ.',
      },
      {
        tag: 'Trút ra',
        title: 'Ra khỏi đầu, thật nhanh',
        body: 'Kể lể hai mươi giây, nói hay gõ đều được. Một việc quay lại; mấy việc kia chờ trong ngăn kéo.',
      },
      {
        tag: 'Sức lực',
        title: 'Vừa với ngày hôm đó',
        body: 'Đuối, tàm tạm hay ổn. Việc được chọn cho vừa sức, và “to quá” làm nó nhỏ lại.',
      },
      {
        tag: 'Thời gian',
        title: 'Thời gian nhìn thấy được',
        body: 'Mười phút hiện ra như một cuộc đua trên màn hình khoá, không phải một con số để thấy tệ.',
      },
      {
        tag: 'Tử tế',
        title: 'Bắt đầu là tính rồi',
        body: '“Chưa xong” là một cách kết thúc bình thường. Không có chuỗi ngày nào để đứt, không bao giờ.',
      },
    ],
  },
  final: {
    headline: 'Bắt con quái đầu tiên ngay tối nay.',
    body: 'Miễn phí trên iPhone. Mười phút. Mang theo cái việc bạn đang né.',
    soonBody: 'Sắp có trên iPhone. Trong lúc chờ, lò ấp vẫn mở.',
    appLine: 'Miễn phí · iPhone',
    get: 'Tải miễn phí',
    orHatch: 'Hoặc ấp thử một con ở đây trước',
    hatchHere: 'Ấp thử một con ở đây',
  },
} as const satisfies Loosen<typeof homeEn>;
