/** The home page below the maker, section by section, in English. */
export const homeEn = {
  hunt: {
    eyebrow: 'How it works · scroll to hunt',
    headline: 'From “ugh” to caught in ten minutes.',
    steps: [
      {
        title: 'Ramble for twenty seconds',
        body: 'Taxes, mum, the dentist, the bathroom. Say all of it.',
      },
      { title: 'One thing hatches', body: 'The rest goes in a drawer. Today it’s Molar.' },
      {
        title: 'The hunt',
        body: 'Scootch runs, Molar shrinks. You can see it on your Lock Screen.',
      },
      { title: 'Catch it. Caught.', body: 'He’s yours for ever, on a card you can tilt.' },
    ],
    task: 'Email the dentist',
    lines: [
      'Molar has no idea what’s coming.',
      'Molar is sweating. Keep going.',
      'Molar is half the size. Ha.',
      'Molar is basically a crumb.',
    ],
    park: 'Park a thought',
    stuck: 'I’m stuck',
    cardTop: 'Caught · 10 min · No. 0043',
    cardTitle: 'Caught.',
    cardBody: 'Molar is on your shelf, sulking. Excellent work.',
  },
  lurk: {
    eyebrow: 'The lurkers',
    headline: 'Ignored things get bigger.',
    body: 'Every day a task waits, its monster grows a little. No streaks, no red badges, no guilt trip. Just a creature that has very clearly outstayed its welcome. Ten minutes shrinks it right back.',
    drag: 'Drag to ignore it longer',
    sliderLabel: 'Days lurking',
    scale: ['Today', 'One week', 'Two weeks'],
    stages: [
      'Day one. Small and polite. Barely noticeable.',
      'A few days in. Settling. Has opinions about your desk.',
      'A week. Has unpacked. Is reading your post.',
      'Pressed against the glass. Ten minutes shrinks it right back.',
    ],
    lurking: 'Lurking',
    day: 'Day {n}',
    unitOne: 'day',
    unitMany: 'days',
    task: 'Do my taxes',
  },
  surfaces: {
    eyebrow: 'Beyond the app',
    headline: 'The hunt follows you everywhere.',
    body: 'On the Lock Screen, in the Dynamic Island and in StandBy. Park a thought or ask for help without unlocking. Start from the Action button, Control Center or a widget, with no app to open and nothing to get lost in.',
    date: 'Thursday 8 October',
    task: 'Email the dentist',
    line: 'Molar is sweating. Keep going.',
    island: 'Dynamic Island · tap it',
    islandLabel: 'Show the next Dynamic Island',
    atTable: '3 at the table',
    caught: 'Caught.',
    caughtLine: 'Molar is on your shelf',
    widgetDay: 'Day 9',
    widgetTask: 'Do my taxes',
    shelf: 'Shelf',
    chips: ['Action button', 'Control Center', 'StandBy', 'Widgets', 'Dynamic Island'],
  },
  tables: {
    eyebrow: 'Tables · body doubling',
    headline: 'Nobody’s talking. Everybody’s doing the thing.',
    body: 'Sit with up to three friends, each doing your own thing. All anyone sees is a word or two about what you’re on. There’s no chat, only quiet company and the odd silent wave.',
    bar: 'Deep work · 4 at the table · 18:40 left',
    wave: 'Send a silent wave',
    waved: 'Waved',
    wavedBack: 'Dana waved back. Back to it.',
    seats: ['You · email', 'Dana · writing', 'Sam · admin', 'Linh · tidying'],
  },
  attitudes: {
    eyebrow: 'Pick an attitude',
    headline: 'Your monsters will text you. Choose how rudely.',
    body: 'Every message is written fresh, about your actual task. Ignore them and they get quieter, never louder. Quiet hours put every monster to bed.',
    pick: 'Attitude',
    names: ['Soft', 'Cheeky', 'Unhinged'],
    senders: ['Molar', 'The Receipt Hydra', 'Scootch'],
    now: 'now',
    notes: [
      [
        'Hi. I’m here. No rush, but Thursday’s getting close.',
        'Nine days together. Ten minutes would make me very small.',
        'Four things done today. Your receipt is attached.',
      ],
      [
        'I’ve moved into your Thursday. I brought a sofa.',
        'Day nine. I’ve started decorating.',
        'Four things done. Receipt attached, as is tradition.',
      ],
      [
        'I have learned to drive. I am coming to Thursday.',
        'DAY NINE. I HAVE A LAWYER NOW. HE IS ALSO A RECEIPT.',
        'FOUR. FOUR THINGS. I have printed a receipt and framed it.',
      ],
    ],
  },
  prices: {
    eyebrow: 'Free for ever · or Plus',
    headline: 'Make it yours, in real materials.',
    body: 'The whole day is free, for ever. Plus adds a bit more Scootch, and your card can wear any of seven finishes. Try one below.',
    finishLabel: 'Finish',
    finishes: ['Paper', 'Holo foil', 'Chrome', 'Jelly', 'Frosted glass', 'Velvet', 'Riso'],
    cardTop: 'Scootch',
    cardNumber: 'No. 0042',
    plans: [
      { name: 'Monthly', price: '$5.99', detail: 'a month' },
      { name: 'Yearly', price: '$39.99', detail: '7 days free first' },
      { name: 'Lifetime', price: '$89.99', detail: 'once, for ever' },
    ],
    freeHeadline: 'Free for ever',
    free: [
      'Up to ten things a day',
      'Every monster you catch, kept',
      'Tables with friends, and a table for two of your own',
      'All three attitudes',
      'The weekly song, and sharing it',
    ],
    plusHeadline: 'Plus adds',
    plus: [
      'Every card finish',
      'Up to twenty-five things a day',
      'Open tables for up to four',
      'The binder, and every weekly record kept',
      'Extra-large widget and StandBy',
    ],
    reminder:
      'I’ll remind you the day before any charge. Cancel in two taps in your Apple settings.',
    allAboutPlus: 'All about Plus',
  },
  share: {
    eyebrow: 'Made to share',
    headline: 'Brag about the tiny wins.',
    body: 'A riso story when you catch something, a receipt of the day’s done things, and a poster at the end of the month. Each one wears your finish.',
    storyLabel: 'A story card: Caught. Lived in my inbox for 11 days. Not any more.',
    storyStamp: 'Caught.',
    storyLine: 'Lived in my inbox for 11 days. Not any more.',
    receiptLabel: 'The day’s receipt: four things done.',
    receiptTitle: 'Done log · Thu 08 Oct',
    receiptRows: [
      ['reply to Sam', '09:12'],
      ['dentist email', '09:41'],
      ['fold laundry', '11:40'],
      ['do my taxes ★', '14:05'],
    ],
    receiptTotal: 'Monsters caught',
    receiptThanks: 'Thank you for shopping at your own life',
    posterLabel: 'The month’s poster: 42 monsters caught in September.',
    posterTitle: 'September',
    posterLine: 'monsters caught.',
  },
  who: {
    eyebrow: 'Who it’s for',
    headline: 'For brains where starting is the hard part.',
    body: 'For people with ADHD, and anyone whose to-do list has its own to-do list. Scootch works from places you already touch, so there are no new habits to keep up.',
    tiles: [
      {
        tag: 'Starting',
        title: 'One press, from anywhere',
        body: 'Action button, a widget, Control Center. You’re going before the doubt kicks in.',
      },
      {
        tag: 'Capture',
        title: 'Out of your head, fast',
        body: 'Ramble for twenty seconds, out loud or typed. One thing comes back; the rest waits in a drawer.',
      },
      {
        tag: 'Energy',
        title: 'Sized to the day',
        body: 'Low, medium or fine. The one thing is picked to fit, and “too big” makes it smaller.',
      },
      {
        tag: 'Time',
        title: 'Time you can see',
        body: 'Ten minutes shown as a race on your Lock Screen, not a number to feel bad about.',
      },
      {
        tag: 'Kindness',
        title: 'Starting counts',
        body: '“Not finished” is a normal way for a session to end. No streaks to break, ever.',
      },
    ],
  },
  final: {
    headline: 'Catch your first monster tonight.',
    body: 'Free on iPhone. Ten minutes. Bring the thing you’ve been avoiding.',
    soonBody: 'Coming to iPhone. Until then, the hatchery is open.',
    appLine: 'Free · iPhone',
    get: 'Get it free',
    orHatch: 'Or hatch one here first',
    hatchHere: 'Hatch one here',
  },
} as const;
