import type { Loosen } from './en';
import type { pagesEn } from './pages-en';

/** The same pages in Vietnamese, written the way a Vietnamese site would say them. */
export const pagesVi = {
  share: {
    share: 'Chia sẻ',
    copied: 'Đã chép đường dẫn: {link}',
    saved: 'Đã lưu. Trang của nó: {link}',
    failed: 'Chưa chia sẻ được con này. Lát nữa thử lại nha.',
    unshare: 'Gỡ chia sẻ',
    unshared: 'Đã gỡ. Trang của nó không còn nữa.',
  },
  monster: {
    title: 'Một con quái hoang · Scootch',
    description: 'Có người vừa biến cái việc đang né thành một con quái. Ấp một con của bạn đi.',
    loading: 'Đang đi bắt con quái về…',
    wildEyebrow: 'Một con quái hoang',
    caughtEyebrow: 'Đã bị bắt',
    wild: 'Hoang',
    caught: 'Đã bắt',
    notCaught: 'Chưa bắt được',
    caughtIn: 'Bắt trong {minutes} phút',
    statusLabel: 'Tình trạng',
    hatchedLabel: 'Nở ngày',
    typedLabel: 'Nó vốn là',
    caughtLabel: 'Bị bắt lúc',
    tookLabel: 'Mất',
    minutes: '{minutes} phút',
    makeYourOwn: 'Ấp một con của bạn',
    catchIt: 'Bắt nó trong app',
    getScootch: 'Tải Scootch',
    cardLabel: '{name}. Một con quái {status}. {flavour}',
    yours: 'Bạn đã chia sẻ con này từ trình duyệt này.',
    offlineTitle: 'Tui chưa lấy được con quái này.',
    offlineBody: 'Bạn xem lại kết nối rồi tải lại trang nha.',
  },
  caughtCard: {
    title: 'Một con quái đã bị bắt · Scootch',
    description: 'Một con quái, đã bị bắt. Ấp một con của bạn trong mười giây.',
    eyebrowBy: '{name} vừa bắt được một con quái',
    eyebrow: 'Có một con quái vừa bị bắt',
    home: '{name} về nhà rồi.',
    story: 'Nó ẩn nấp {days}. Bị bắt trong {duration}.',
    lurked: 'Ẩn nấp',
    caughtIn: 'Bắt trong',
    rarity: 'Độ hiếm',
    number: 'Thẻ',
    caughtOn: 'Ngày bắt',
    task: 'Nó vốn là',
    tiltPointer: 'Rê chuột lên tấm thẻ để nghiêng nó.',
    tiltMotion: 'Nghiêng thẻ bằng điện thoại',
    cardLabel: '{name}. Bị bắt trong {duration}. {flavour}',
    askTitle: 'Bạn cũng đang né việc gì đó?',
    askBody: 'Biến nó thành một con quái trong mười giây. Không cần đăng ký.',
    makeYourOwn: 'Ấp một con quái của bạn',
    onlyShownBy: 'Chia sẻ từ Scootch. Chỉ có những gì {name} chọn cho xem.',
    onlyShown: 'Chia sẻ từ Scootch. Chỉ có những gì người chia sẻ chọn cho xem.',
  },
  story: {
    title: 'Làm xong việc đó rồi · Scootch',
    description: 'Một việc nhỏ, đã bắt đầu và đã xong. Ấp một con quái của bạn đi.',
    waited: 'Để tận {days}.',
    took: 'Làm mất {duration}.',
  },
  notFound: {
    title: 'Trang này bị ăn mất rồi · Scootch',
    eyebrow: '404 · một con Lạc Lối hoang xuất hiện',
    headline: 'Trang này bị ăn mất rồi.',
    body: 'Lạc Lối, Kẻ Ăn Trang, chỉ sống ở đây chứ không ở đâu khác. Trông nó khá đắc ý.',
    cardName: 'Lạc Lối, Kẻ Ăn Trang',
    cardFlavour: 'Ăn mất trang bạn cần. Vẫn còn đói.',
    make: 'Ấp một con quái thay vậy',
    home: 'Về trang chủ',
  },
  plus: {
    title: 'Scootch Plus · giá và nội quy',
    description: 'Cái gì miễn phí mãi mãi, Plus thêm gì, ba mức giá, và nội quy của Plus.',
    eyebrow: 'Scootch Plus',
    headline: 'Tui làm không công. Tui muốn làm với giá nhỉnh hơn không công một chút.',
    sub: 'Plus là vài món thêm cho người dùng Scootch nhiều. Còn điều quan trọng nhất, bắt đầu một việc nhỏ, thì miễn phí mãi mãi.',
    plans: [
      { name: 'Hằng tháng', price: '$5.99', detail: 'mỗi tháng', note: 'Hủy tháng nào cũng được' },
      {
        name: 'Hằng năm',
        price: '$39.99',
        detail: 'mỗi năm, chừng $3.33 một tháng',
        note: '7 ngày đầu miễn phí',
      },
      { name: 'Trọn đời', price: '$89.99', detail: 'một lần', note: 'Không bao giờ gia hạn' },
    ],
    priceNote:
      'Giá tính bằng USD. Giá trên App Store ở nước bạn có thể khác. Gói đăng ký tự gia hạn cho tới khi bạn hủy trong cài đặt Apple, mục Đăng ký.',
    freeTitle: 'Miễn phí mãi mãi',
    free: [
      'Mỗi ngày tới mười việc, mãi mãi',
      'Mọi con quái bạn bắt được, giữ mãi mãi',
      'Ngồi bàn với bạn bè, và tự mở bàn hai chỗ',
      'Cả ba kiểu tính cách',
      'Bài hát mỗi tuần, và chia sẻ mọi thứ',
    ],
    addsTitle: 'Plus thêm gì',
    adds: [
      {
        title: 'Nhiều việc hơn mỗi ngày',
        body: 'Có Plus thì mỗi ngày tới hai mươi lăm việc. Mười việc thì miễn phí, mãi mãi.',
      },
      { title: 'Bàn rộng hơn', body: 'Mở bàn bốn chỗ và rủ ba người bạn ngồi miễn phí.' },
      {
        title: 'Một Scootch hiểu bạn',
        body: 'Nó tự học xem bạn bắt đầu dễ nhất lúc nào, kiểu nào.',
      },
      { title: 'Giữ mọi bản nhạc', body: 'Trọn bài, mỗi tuần, giữ lại và xuất ra được.' },
      { title: 'Cuốn sưu tập', body: 'Sắp xếp bầy quái, và in thẻ bằng những lớp phủ khác.' },
      { title: 'Widget cỡ lớn', body: 'Widget cực lớn và StandBy toàn màn hình.' },
    ],
    rulesTitle: 'Nội quy',
    rules: [
      {
        title: 'Không bao giờ bán',
        body: 'Độ hiếm, gói ngẫu nhiên, xu, hay bù cho một ngày nghỉ. Không mua được con quái xịn hơn.',
      },
      {
        title: 'Luôn miễn phí',
        body: 'Việc bắt đầu. Trọn vòng một ngày. Mọi kiểu tính cách. Chia sẻ.',
      },
      {
        title: 'Không chắn đường',
        body: 'Không mời mua lúc mở app lần đầu, trên màn hình chính, giữa phiên làm việc, hay ở “Hôm nay xong rồi”.',
      },
      {
        title: 'Trước mỗi lần trừ tiền',
        body: 'Luôn có lời nhắc trước khi tiền bị trừ, kể cả một ngày trước khi hết dùng thử.',
      },
      {
        title: 'Khi rời đi',
        body: 'Hủy trong cài đặt Apple. iPhone không có nút tạm dừng. Bạn giữ mọi thứ đã bắt được.',
      },
    ],
    buy: 'Ở đây không có nút mua. Bạn mua Plus ngay trong app, qua Apple.',
    buySoon: 'Ở đây không có nút mua. Khi app ra mắt, bạn mua Plus ngay trong app, qua Apple.',
  },
  preLaunch: {
    comingSoon: 'Sắp có trên iPhone',
    tellMe: 'Báo tui',
    intro: 'Scootch chưa ra mắt. Để lại email, tui giữ con quái này cho bạn.',
    introPlain: 'Scootch chưa ra mắt. Để lại email, ngày nào ra tui báo liền.',
    emailLabel: 'Email của bạn',
    emailPlaceholder: 'ban@example.com',
    submit: 'Báo tui khi ra mắt',
    note: 'Đúng một email vào ngày ra mắt. Vậy thôi.',
    done: 'Xong. Tui giữ {name} cẩn thận tới ngày ra mắt.',
    donePlain: 'Xong. Đúng một email vào ngày ra mắt, vậy thôi.',
    badEmail: 'Cái này chưa giống email lắm. Bạn gõ lại thử nha.',
    failed: 'Chưa gửi được. Lát nữa thử lại nha.',
  },
  android: {
    title: 'Scootch trên Android: chưa có',
    description: 'Hiện Scootch chỉ có trên iPhone. Để lại email để biết ngày Android sẵn sàng.',
    headline: 'Chưa có, xin lỗi nha.',
    body: 'Hiện Scootch chỉ có trên iPhone. Android nằm trong kế hoạch, nhưng chưa có ngày. Để lại email, ngày nào ra tui báo liền.',
    submit: 'Báo tui khi có',
    note: 'Đúng một email vào ngày Scootch có trên Android. Không có bản tin.',
    done: 'Ghi rồi. Bạn sẽ là người biết đầu tiên.',
    maker: 'Lò ấp quái thì chạy được trên Android ngay bây giờ.',
    tryIt: 'Thử liền',
  },
} as const satisfies Loosen<typeof pagesEn>;
