import { helpEn } from './help-en';

/** The words of the shared pages, the Plus page and the pages around launch, in English. */
export const pagesEn = {
  share: {
    share: 'Share',
    copied: 'Link copied: {link}',
    saved: 'Saved. Its page: {link}',
    failed: 'Couldn’t share that one. Try again in a bit.',
    unshare: 'Unshare',
    unshared: 'Unshared. Its page is gone.',
  },
  monster: {
    title: 'A wild monster · Scootch',
    description: 'Someone turned a thing they were avoiding into a monster. Make your own.',
    loading: 'Fetching the monster…',
    wildEyebrow: 'A wild monster',
    caughtEyebrow: 'Caught',
    wild: 'Wild',
    caught: 'Caught',
    notCaught: 'Not caught yet',
    caughtIn: 'Caught in {minutes} min',
    statusLabel: 'Status',
    hatchedLabel: 'Hatched',
    typedLabel: 'It was',
    caughtLabel: 'Caught',
    tookLabel: 'It took',
    minutes: '{minutes} min',
    makeYourOwn: 'Make your own',
    catchIt: 'Catch it in the app',
    getScootch: 'Get Scootch',
    cardLabel: '{name}. A {status} monster. {flavour}',
    yours: 'You shared this one from this browser.',
    offlineTitle: 'I couldn’t fetch this monster.',
    offlineBody: 'Check your connection and load the page again.',
    turnEyebrow: 'Your turn',
    turnTitle: 'Got a lurker of your own?',
    turnBody:
      'Type the thing you’ve been avoiding. It hatches in two seconds, and nothing is kept unless you share it.',
    turnField: 'What have you been avoiding?',
    turnPlaceholder: 'e.g. replying to mum',
    turnHatch: 'Hatch it',
    turnExamples: ['replying to mum', 'the gym', 'my taxes', 'the bathroom'],
    note: 'Whoever hatched this chose to share it. What they typed shows only if they left it showing, and the page names nobody.',
    address: 'scootch.app/m',
  },
  caughtCard: {
    title: 'A caught monster · Scootch',
    description: 'A monster, caught. Make your own in ten seconds.',
    eyebrowBy: '{name} caught a monster',
    eyebrow: 'A monster got caught',
    home: '{name} is home.',
    story: 'It lurked for {days}. It was caught in {duration}.',
    lurked: 'Lurked for',
    caughtIn: 'Caught in',
    rarity: 'Rarity',
    number: 'Card',
    caughtOn: 'Caught',
    task: 'It was',
    tiltPointer: 'Move your pointer over the card to tilt it.',
    tiltMotion: 'Tilt the card with your phone',
    cardLabel: '{name}. Caught in {duration}. {flavour}',
    askTitle: 'Got something you’re avoiding?',
    askBody: 'Turn it into a monster in ten seconds. No sign-up.',
    makeYourOwn: 'Make your own monster',
    onlyShownBy: 'Shared from Scootch. Only what {name} chose to show.',
    onlyShown: 'Shared from Scootch. Only what the sharer chose to show.',
  },
  story: {
    title: 'Did the thing · Scootch',
    description: 'One small thing, started and done. Make your own monster.',
    waited: 'It waited {days}.',
    took: 'Took {duration}.',
  },
  notFound: {
    title: 'This page wandered off · Scootch',
    eyebrow: 'Page not found',
    headline: 'This page wandered off. Classic.',
    body: 'It was here a minute ago. Odd Sock may have taken it. Try one of these instead.',
    home: 'Back home',
    make: 'Hatch a monster',
    help: 'Help',
  },
  plus: {
    title: 'Scootch Plus · prices and house rules',
    description:
      'What is free for ever, what Plus adds, three prices, and the rules Plus plays by.',
    eyebrow: 'Scootch Plus',
    headline: 'I work for free. I’d like to work for slightly more than free.',
    sub: 'Plus is a few extras for people who use Scootch a lot. The thing that matters, starting one small thing, is free for ever.',
    plans: [
      { name: 'Monthly', price: '$5.99', detail: 'a month', note: 'Cancel any month' },
      {
        name: 'Yearly',
        price: '$39.99',
        detail: 'a year, about $3.33 a month',
        note: '7 days free first',
      },
      { name: 'Lifetime', price: '$89.99', detail: 'once', note: 'Nothing ever renews' },
    ],
    priceNote:
      'Prices in USD. Your local App Store price may differ. Subscriptions renew until you cancel them in your Apple settings, under Subscriptions.',
    freeTitle: 'Free for ever',
    free: [
      'Up to ten things a day, for ever',
      'Every monster you catch, for ever',
      'Tables with friends, and a table for two of your own',
      'All three attitudes',
      'The weekly song, and sharing everything',
    ],
    addsTitle: 'What Plus adds',
    adds: [
      {
        title: 'More in a day',
        body: 'Up to twenty-five things a day with Plus. Ten are free, for ever.',
      },
      { title: 'Bigger tables', body: 'Open a table for four and bring three friends free.' },
      { title: 'A Scootch that learns you', body: 'It works out when and how you start best.' },
      { title: 'Keep every record', body: 'The full track, every week, to keep and export.' },
      { title: 'The binder', body: 'Sort your monsters, and print cards in extra finishes.' },
      { title: 'Big widgets', body: 'Extra-large widget and full-screen StandBy.' },
    ],
    rulesTitle: 'House rules',
    rules: [
      {
        title: 'Never sold',
        body: 'Rarity, random packs, coins, or making up for a day off. You can’t buy a better monster.',
      },
      { title: 'Always free', body: 'Starting. The whole day loop. Every attitude. Sharing.' },
      {
        title: 'Never in the way',
        body: 'No offer on first launch, on the one screen, in a session, or on “Done for today”.',
      },
      {
        title: 'Before every charge',
        body: 'A reminder goes out before any money moves, including the day before a trial ends.',
      },
      {
        title: 'Leaving',
        body: 'Cancel in your Apple settings. There’s no pause on iPhone. You keep everything you caught.',
      },
    ],
    buy: 'There’s no buy button here. You buy Plus inside the app, through Apple.',
    buySoon:
      'There’s no buy button here. Once the app is out, you buy Plus inside it, through Apple.',
    heroWords: ['A bit', 'more', 'Scootch.'],
    heroSub:
      'Everything that matters is free, for ever. Plus is for people who want their monsters in chrome.',
    finishLabel: 'Finish {n}',
    fanLabel:
      'Seven card finishes: Paper, Riso, Jelly, Holo foil, Chrome, Frosted glass and Velvet.',
    finishes: ['Paper', 'Riso', 'Jelly', 'Holo foil', 'Chrome', 'Frosted glass', 'Velvet'],
    plansTitle: 'Three ways to pay',
    picked: 'The one most people pick',
    get: 'Get the app',
    insideTitle: 'What’s inside the shiny box',
    finishesEyebrow: 'Finishes',
    finishesTitle: 'Seven materials, built from light',
    finishesBody:
      'Foil, chrome, jelly, glass, velvet and riso. Your cards, stickers and shares all wear the one you pick.',
    answersTitle: 'Honest answers',
    answers: [
      {
        q: 'Will you remind me before I’m charged?',
        a: 'Yes. A reminder goes out before any money moves, including the day before a trial ends, in plain words, with the date and the amount.',
      },
      {
        q: 'How do I cancel?',
        a: 'In your Apple settings: your name, then Subscriptions, then Scootch. There’s no pause on iPhone, only cancel, and nobody asks you to explain yourself.',
      },
      {
        q: 'What happens to my stuff if I stop?',
        a: 'You keep everything you caught, every card and your whole world. Finishes you didn’t buy on their own go back to paper, and that’s it.',
      },
      {
        q: 'Is the free version a trap?',
        a: 'No. Starting, the whole day loop, every attitude and sharing are free, for ever. There’s no offer on first launch, on the one screen, in a session, or on “Done for today”.',
      },
      {
        q: 'What can’t I buy?',
        a: 'Rarity, random packs, coins, or making up for a day off. You can’t buy a better monster.',
      },
    ],
  },
  preLaunch: {
    comingSoon: 'Coming soon to iPhone',
    tellMe: 'Tell me',
    intro: 'Scootch isn’t out yet. Leave an email and I’ll keep this monster for you.',
    introPlain: 'Scootch isn’t out yet. Leave an email and I’ll tell you the day it is.',
    emailLabel: 'Your email',
    emailPlaceholder: 'you@example.com',
    submit: 'Tell me when it’s out',
    note: 'One email on launch day. That’s it.',
    done: 'Done. I’ll keep {name} safe until launch day.',
    donePlain: 'Done. One email on launch day, and that’s it.',
    badEmail: 'That doesn’t look like an email. Have another go.',
    failed: 'That didn’t go through. Try again in a bit.',
  },
  android: {
    title: 'Scootch on Android: not yet',
    description: 'Scootch is iPhone-only for now. Leave an email to hear the day Android is ready.',
    headline: 'Not yet, sorry.',
    body: 'Scootch is iPhone-only for now. Android is planned, but there’s no date. Leave an email and I’ll tell you the day it’s out.',
    submit: 'Tell me when it’s ready',
    note: 'One email the day Scootch lands on Android. No newsletter.',
    done: 'Noted. You’ll be first to know.',
    maker: 'The monster maker works on Android right now.',
    tryIt: 'Try it',
  },
  ...helpEn,
} as const;
