/** The words of the shared pages, the Plus page and the pages around launch, in English. */
export const pagesEn = {
  share: {
    share: 'Share',
    copied: 'Link copied: {link}',
    saved: 'Saved. Its page: {link}',
    failed: 'Couldn’t share that one. Try again in a bit.',
    unshare: 'Unshare',
    unshared: 'Unshared. Its page is gone.',
  },
  monster: {
    title: 'A wild monster · Scootch',
    description: 'Someone turned a thing they were avoiding into a monster. Make your own.',
    loading: 'Fetching the monster…',
    wildEyebrow: 'A wild monster',
    caughtEyebrow: 'Caught',
    wild: 'Wild',
    caught: 'Caught',
    notCaught: 'Not caught yet',
    caughtIn: 'Caught in {minutes} min',
    statusLabel: 'Status',
    hatchedLabel: 'Hatched',
    typedLabel: 'It was',
    caughtLabel: 'Caught',
    tookLabel: 'It took',
    minutes: '{minutes} min',
    makeYourOwn: 'Make your own',
    catchIt: 'Catch it in the app',
    getScootch: 'Get Scootch',
    cardLabel: '{name}. A {status} monster. {flavour}',
    yours: 'You shared this one from this browser.',
    offlineTitle: 'I couldn’t fetch this monster.',
    offlineBody: 'Check your connection and load the page again.',
  },
  caughtCard: {
    title: 'A caught monster · Scootch',
    description: 'A monster, caught. Make your own in ten seconds.',
    eyebrowBy: '{name} caught a monster',
    eyebrow: 'A monster got caught',
    home: '{name} is home.',
    story: 'It lurked for {days}. It was caught in {duration}.',
    lurked: 'Lurked for',
    caughtIn: 'Caught in',
    rarity: 'Rarity',
    number: 'Card',
    caughtOn: 'Caught',
    task: 'It was',
    tiltPointer: 'Move your pointer over the card to tilt it.',
    tiltMotion: 'Tilt the card with your phone',
    cardLabel: '{name}. Caught in {duration}. {flavour}',
    askTitle: 'Got something you’re avoiding?',
    askBody: 'Turn it into a monster in ten seconds. No sign-up.',
    makeYourOwn: 'Make your own monster',
    onlyShownBy: 'Shared from Scootch. Only what {name} chose to show.',
    onlyShown: 'Shared from Scootch. Only what the sharer chose to show.',
  },
  story: {
    title: 'Did the thing · Scootch',
    description: 'One small thing, started and done. Make your own monster.',
    waited: 'It waited {days}.',
    took: 'Took {duration}.',
  },
  notFound: {
    title: 'This page got eaten · Scootch',
    eyebrow: '404 · a wild Lostling appeared',
    headline: 'This page got eaten.',
    body: 'Lostling, Eater of Pages, lives here and nowhere else. It looks pleased with itself.',
    cardName: 'Lostling, Eater of Pages',
    cardFlavour: 'Ate the page you wanted. Still hungry.',
    make: 'Make a monster instead',
    home: 'Go home',
  },
  plus: {
    title: 'Scootch Plus · prices and house rules',
    description:
      'What is free for ever, what Plus adds, three prices, and the rules Plus plays by.',
    eyebrow: 'Scootch Plus',
    headline: 'I work for free. I’d like to work for slightly more than free.',
    sub: 'Plus is a few extras for people who use Scootch a lot. The thing that matters, starting one small thing, is free for ever.',
    plans: [
      { name: 'Monthly', price: '$5.99', detail: 'a month', note: 'Cancel any month' },
      {
        name: 'Yearly',
        price: '$39.99',
        detail: 'a year, about $3.33 a month',
        note: '7 days free first',
      },
      { name: 'Lifetime', price: '$89.99', detail: 'once', note: 'Nothing ever renews' },
    ],
    priceNote:
      'Prices in USD. Your local App Store price may differ. Subscriptions renew until you cancel them in your Apple settings, under Subscriptions.',
    freeTitle: 'Free for ever',
    free: [
      'One thing a day, for ever',
      'Every monster you catch, for ever',
      'Tables with friends',
      'All three attitudes',
      'The weekly song, and sharing everything',
    ],
    addsTitle: 'What Plus adds',
    adds: [
      { title: 'One more, or two', body: 'A second and third thing on days you’ve got it in you.' },
      { title: 'Your own tables', body: 'Open a table and bring up to three friends free.' },
      { title: 'A Scootch that learns you', body: 'It works out when and how you start best.' },
      { title: 'Keep every record', body: 'The full track, every week, to keep and export.' },
      { title: 'The binder', body: 'Sort your monsters, and print cards in extra finishes.' },
      { title: 'Big widgets', body: 'Extra-large widget and full-screen StandBy.' },
    ],
    rulesTitle: 'House rules',
    rules: [
      {
        title: 'Never sold',
        body: 'Rarity, random packs, coins, or making up for a day off. You can’t buy a better monster.',
      },
      { title: 'Always free', body: 'Starting. The whole day loop. Every attitude. Sharing.' },
      {
        title: 'Never in the way',
        body: 'No offer on first launch, on the one screen, in a session, or on “Done for today”.',
      },
      {
        title: 'Before every charge',
        body: 'A reminder goes out before any money moves, including the day before a trial ends.',
      },
      {
        title: 'Leaving',
        body: 'Cancel in your Apple settings. There’s no pause on iPhone. You keep everything you caught.',
      },
    ],
    buy: 'There’s no buy button here. You buy Plus inside the app, through Apple.',
    buySoon:
      'There’s no buy button here. Once the app is out, you buy Plus inside it, through Apple.',
  },
  preLaunch: {
    comingSoon: 'Coming soon to iPhone',
    tellMe: 'Tell me',
    intro: 'Scootch isn’t out yet. Leave an email and I’ll keep this monster for you.',
    introPlain: 'Scootch isn’t out yet. Leave an email and I’ll tell you the day it is.',
    emailLabel: 'Your email',
    emailPlaceholder: 'you@example.com',
    submit: 'Tell me when it’s out',
    note: 'One email on launch day. That’s it.',
    done: 'Done. I’ll keep {name} safe until launch day.',
    donePlain: 'Done. One email on launch day, and that’s it.',
    badEmail: 'That doesn’t look like an email. Have another go.',
    failed: 'That didn’t go through. Try again in a bit.',
  },
  android: {
    title: 'Scootch on Android: not yet',
    description: 'Scootch is iPhone-only for now. Leave an email to hear the day Android is ready.',
    headline: 'Not yet, sorry.',
    body: 'Scootch is iPhone-only for now. Android is planned, but there’s no date. Leave an email and I’ll tell you the day it’s out.',
    submit: 'Tell me when it’s ready',
    note: 'One email the day Scootch lands on Android. No newsletter.',
    done: 'Noted. You’ll be first to know.',
    maker: 'The monster maker works on Android right now.',
    tryIt: 'Try it',
  },
} as const;
