/** The words of the table invite, haunt and record pages, in English. */
export const togetherEn = {
  invite: {
    title: 'A seat is saved · Scootch',
    description: 'One small thing each, quietly, together.',
    loading: 'Finding the table…',
    hereNow: '{count} here now',
    headlineBy: '{name} saved you a seat.',
    headline: 'A seat is saved for you.',
    seatName: 'Someone',
    you: 'You?',
    savedForYou: 'saved for you',
    seatsLabel: 'Who is at the table',
    body: 'Sit down, pick one small thing, say nothing. Nobody sees your list, only a one-word label.',
    bodyDesk:
      'Tables are for doing your own thing next to other people. No chat, no camera. Nobody sees your list.',
    sitDown: 'Sit down',
    note: 'Opens Scootch, or the App Store if you don’t have it yet. Your seat is held for 10 minutes.',
    deskTitle: 'Open this link on your iPhone to sit down.',
    deskNote: 'Seat held for 10 minutes.',
    closedEyebrow: 'This seat went cold',
    closedHeadlineByAt: '{name}’s table closed at {time}.',
    closedHeadlineBy: '{name}’s table has closed.',
    closedHeadlineAt: 'This table closed at {time}.',
    closedHeadline: 'This table has closed.',
    closedBodyBy: 'Invites last as long as the table. {name} can save you a new seat any time.',
    closedBody: 'Invites last as long as the table. Your friend can save you a new seat any time.',
    getScootch: 'Get Scootch',
    makeMeanwhile: 'Make a monster meanwhile',
    offlineTitle: 'I couldn’t find this table.',
    offlineBody: 'Check your connection and load the page again.',
  },
  haunt: {
    title: 'A monster is waiting · Scootch',
    description: 'Someone sent you a monster. Catch it or shoo it.',
    loading: 'Fetching the monster…',
    eyebrow: 'You’ve been haunted',
    headlineBy: '{name} sent you a monster.',
    headline: 'Someone sent you a monster.',
    dare: 'Dare: “{dare}”',
    monsterLabel: 'The monster that was sent to you',
    shoo: 'Shoo it',
    catchIt: 'Catch it · 10 min',
    shooFailed: 'Couldn’t shoo it just now. Try again in a bit.',
    shooedTitle: 'Shooed.',
    shooedBodyBy: 'It wandered off. Nobody was told, not even {name}.',
    shooedBody: 'It wandered off. Nobody was told.',
    goneTitle: 'It wandered off.',
    goneBody: 'This monster isn’t waiting here any more.',
    makeYourOwn: 'Make your own monster',
    turnOff: 'Don’t want to be haunted again? Turn haunting off in the app, under Friends.',
    offlineTitle: 'I couldn’t fetch this monster.',
    offlineBody: 'Check your connection and load the page again.',
  },
  record: {
    title: 'A week, as a record · Scootch',
    description: 'A week, as a record. 15 seconds. Press play.',
    loading: 'Finding the record…',
    eyebrowBy: '{name}’s week · {dates}',
    eyebrow: 'A week · {dates}',
    bars: '{count} bars',
    oneBar: '1 bar',
    fullBand: 'full band',
    smallBand: 'a smaller band',
    play: 'Play',
    pause: 'Pause',
    caption: 'A 15-second clip. Every bar is one finished day.',
    noClip: 'The clip won’t play right now. The track list is all here.',
    tracksLabel: 'The week’s tracks',
    discLabel: 'The record’s sleeve',
    offlineTitle: 'I couldn’t find this record.',
    offlineBody: 'Check your connection and load the page again.',
  },
} as const;
