/** The words of the table invite, haunt and record pages, in English. */
export const togetherEn = {
  invite: {
    title: 'A seat is saved · Scootch',
    description: 'One small thing each, quietly, together.',
    loading: 'Finding the table…',
    hereNow: '{count} here now',
    headlineBy: '{name} saved you a seat.',
    headline: 'A seat is saved for you.',
    seatName: 'Someone',
    you: 'You?',
    savedForYou: 'saved for you',
    seatsLabel: 'Who is at the table',
    body: 'Sit down, pick one small thing, say nothing. Nobody sees your list, only a one-word label.',
    bodyDesk:
      'Tables are for doing your own thing next to other people. No chat, no camera. Nobody sees your list.',
    sitDown: 'Sit down',
    note: 'Opens Scootch if you have it, or the App Store if you don’t.',
    deskTitle: 'Open this link on your iPhone to sit down.',
    deskNote: 'Tables live in the iPhone app.',
    closedEyebrow: 'This seat went cold',
    closedHeadlineByAt: '{name}’s table closed at {time}.',
    closedHeadlineBy: '{name}’s table has closed.',
    closedHeadlineAt: 'This table closed at {time}.',
    closedHeadline: 'This table has closed.',
    closedBodyBy: 'Invites last as long as the table. {name} can save you a new seat any time.',
    closedBody: 'Invites last as long as the table. Your friend can save you a new seat any time.',
    getScootch: 'Get Scootch',
    makeMeanwhile: 'Make a monster meanwhile',
    offlineTitle: 'I couldn’t find this table.',
    offlineBody: 'Check your connection and load the page again.',
  },
  friend: {
    title: 'A friend link · Scootch',
    description: 'Friends on Scootch sit at each other’s tables. Nobody sees your list.',
    loading: 'Finding the link…',
    eyebrow: 'A friend link',
    headlineBy: '{name} wants to sit with you.',
    headline: 'Someone wants to sit with you.',
    body: 'Friends on Scootch can sit at each other’s tables and send each other a monster. Nobody sees your list.',
    accept: 'Be friends in Scootch',
    goneTitle: 'This link has been used up.',
    goneBody: 'A friend link works once, for a week. Your friend can send you a new one any time.',
    getScootch: 'Get Scootch',
    makeMeanwhile: 'Make a monster meanwhile',
    offlineTitle: 'I couldn’t find this link.',
    offlineBody: 'Check your connection and load the page again.',
  },
  get: {
    title: 'Catch it in the app · Scootch',
    description: 'Take your monster with you into Scootch.',
    loading: 'Fetching the monster…',
    eyebrow: 'Catch it in the app',
    headlineBy: '{name} is coming with you.',
    phoneBody:
      'Open Scootch and it will be waiting there. No Scootch yet? Get it, then open this link again.',
    open: 'Open in Scootch',
    deskBody: 'Scootch lives on your iPhone. Point its camera here and the monster comes along.',
    deskTitle: 'Scan this with your iPhone.',
    qrLabel: 'A QR code that opens this monster in Scootch',
    orLink: 'Or open this link on your iPhone: ',
    offlineTitle: 'I couldn’t fetch this monster.',
    offlineBody: 'Check your connection and load the page again.',
  },
  handOff: {
    pasteLine: 'Nothing opened? Copy this code and paste it in Scootch, under “Sit with someone”.',
    codeLabel: 'The code',
    copy: 'Copy code',
    copied: 'Copied.',
  },
  haunt: {
    title: 'A monster is waiting · Scootch',
    description: 'Someone sent you a monster. Catch it or shoo it.',
    loading: 'Fetching the monster…',
    eyebrow: 'You’ve been haunted',
    headlineBy: '{name} sent you a monster.',
    headline: 'Someone sent you a monster.',
    dare: 'Dare: “{dare}”',
    monsterLabel: 'The monster that was sent to you',
    shoo: 'Shoo it',
    catchIt: 'Catch it · 10 min',
    shooFailed: 'Couldn’t shoo it just now. Try again in a bit.',
    shooedTitle: 'Shooed.',
    shooedBodyBy: 'It wandered off. Nobody was told, not even {name}.',
    shooedBody: 'It wandered off. Nobody was told.',
    goneTitle: 'It wandered off.',
    goneBody: 'This monster isn’t waiting here any more.',
    makeYourOwn: 'Make your own monster',
    turnOff: 'Don’t want to be haunted again? Turn haunting off in the app, under Friends.',
    offlineTitle: 'I couldn’t fetch this monster.',
    offlineBody: 'Check your connection and load the page again.',
  },
  record: {
    title: 'A week, as a record · Scootch',
    description: 'A week, as a record. 15 seconds. Press play.',
    loading: 'Finding the record…',
    eyebrowBy: '{name}’s week · {dates}',
    eyebrow: 'A week · {dates}',
    bars: '{count} bars',
    oneBar: '1 bar',
    fullBand: 'full band',
    smallBand: 'a smaller band',
    play: 'Play',
    pause: 'Pause',
    caption: 'A 15-second clip. Every bar is one finished day.',
    noClip: 'The clip won’t play right now. The track list is all here.',
    tracksLabel: 'The week’s tracks',
    discLabel: 'The record’s sleeve',
    offlineTitle: 'I couldn’t find this record.',
    offlineBody: 'Check your connection and load the page again.',
  },
} as const;
