import type { Loosen } from './en';
import type { togetherEn } from './together-en';

/** The same pages in Vietnamese, written the way a Vietnamese site would say them. */
export const togetherVi = {
  invite: {
    title: 'Có một chỗ đang giữ cho bạn · Scootch',
    description: 'Mỗi người một việc nhỏ, lặng lẽ, bên nhau.',
    loading: 'Đang tìm bàn…',
    hereNow: '{count} người đang ngồi',
    headlineBy: '{name} giữ chỗ cho bạn rồi.',
    headline: 'Có một chỗ đang giữ cho bạn.',
    seatName: 'Ai đó',
    you: 'Bạn?',
    savedForYou: 'giữ cho bạn',
    seatsLabel: 'Những ai đang ngồi ở bàn',
    body: 'Ngồi xuống, chọn một việc nhỏ, khỏi nói gì. Không ai thấy danh sách của bạn, chỉ thấy một cái nhãn một chữ.',
    bodyDesk:
      'Bàn là nơi ai làm việc nấy, cạnh nhau. Không chat, không camera. Không ai thấy danh sách của bạn.',
    sitDown: 'Ngồi xuống',
    note: 'Mở Scootch, hoặc App Store nếu bạn chưa có. Chỗ của bạn được giữ 10 phút.',
    deskTitle: 'Mở đường dẫn này trên iPhone để ngồi xuống.',
    deskNote: 'Chỗ được giữ 10 phút.',
    closedEyebrow: 'Chỗ này nguội mất rồi',
    closedHeadlineByAt: 'Bàn của {name} đã đóng lúc {time}.',
    closedHeadlineBy: 'Bàn của {name} đã đóng.',
    closedHeadlineAt: 'Bàn này đã đóng lúc {time}.',
    closedHeadline: 'Bàn này đã đóng.',
    closedBodyBy: 'Lời mời còn chừng nào bàn còn. {name} giữ chỗ mới cho bạn lúc nào cũng được.',
    closedBody: 'Lời mời còn chừng nào bàn còn. Bạn của bạn giữ chỗ mới lúc nào cũng được.',
    getScootch: 'Tải Scootch',
    makeMeanwhile: 'Trong lúc chờ, ấp một con quái',
    offlineTitle: 'Mình chưa tìm được bàn này.',
    offlineBody: 'Kiểm tra kết nối rồi tải lại trang nha.',
  },
  haunt: {
    title: 'Có một con quái đang chờ · Scootch',
    description: 'Có người gửi cho bạn một con quái. Bắt nó hoặc xua nó đi.',
    loading: 'Đang đi bắt con quái…',
    eyebrow: 'Bạn bị ám rồi',
    headlineBy: '{name} gửi cho bạn một con quái.',
    headline: 'Có người gửi cho bạn một con quái.',
    dare: 'Lời thách: “{dare}”',
    monsterLabel: 'Con quái được gửi cho bạn',
    shoo: 'Xua nó đi',
    catchIt: 'Bắt nó · 10 phút',
    shooFailed: 'Chưa xua được nó. Lát nữa thử lại nha.',
    shooedTitle: 'Xua rồi.',
    shooedBodyBy: 'Nó lững thững đi mất. Không ai được báo, kể cả {name}.',
    shooedBody: 'Nó lững thững đi mất. Không ai được báo.',
    goneTitle: 'Nó đi mất rồi.',
    goneBody: 'Con quái này không còn chờ ở đây nữa.',
    makeYourOwn: 'Ấp một con quái của bạn',
    turnOff: 'Không muốn bị ám nữa? Tắt phần ám trong ứng dụng, ở mục Bạn bè.',
    offlineTitle: 'Mình chưa bắt được con quái này về.',
    offlineBody: 'Kiểm tra kết nối rồi tải lại trang nha.',
  },
  record: {
    title: 'Một tuần, thành một đĩa nhạc · Scootch',
    description: 'Một tuần, thành một đĩa nhạc. 15 giây. Bấm nghe thử.',
    loading: 'Đang tìm đĩa nhạc…',
    eyebrowBy: 'Tuần của {name} · {dates}',
    eyebrow: 'Một tuần · {dates}',
    bars: '{count} ô nhịp',
    oneBar: '1 ô nhịp',
    fullBand: 'đủ ban nhạc',
    smallBand: 'ban nhạc nhỏ hơn',
    play: 'Phát',
    pause: 'Tạm dừng',
    caption: 'Một đoạn 15 giây. Mỗi ô nhịp là một ngày đã xong.',
    noClip: 'Lúc này chưa phát được đoạn nhạc. Danh sách bài vẫn ở đây.',
    tracksLabel: 'Các bài trong tuần',
    discLabel: 'Bìa đĩa nhạc',
    offlineTitle: 'Mình chưa tìm được đĩa nhạc này.',
    offlineBody: 'Kiểm tra kết nối rồi tải lại trang nha.',
  },
} satisfies Loosen<typeof togetherEn>;
