import type { SiteCopy } from './en';
import { homeVi } from './home-vi';

/**
 * The website's words in Vietnamese, written as a Vietnamese site would say them rather than word
 * for word. Scootch calls itself "tui".
 */
export const vi = {
  meta: {
    title: 'Scootch: bạn đang né việc gì vậy?',
    description:
      'Gõ cái việc bạn đang né. Scootch biến nó thành một con quái, rồi ngồi cùng bạn bắt đầu: mỗi ngày một việc nhỏ.',
  },
  nav: {
    label: 'Chính',
    maker: 'Lò ấp quái',
    how: 'Cách dùng',
    tables: 'Ngồi chung bàn',
    help: 'Trợ giúp',
    menu: 'Menu',
    getTheApp: 'Tải app',
    skip: 'Tới thẳng lò ấp quái',
  },
  badge: { alt: 'Tải về trên App Store' },
  footer: {
    tagline: 'Từng việc nhỏ một, có người ngồi lặng lẽ bên cạnh.',
    scootch: 'Scootch',
    whatItIs: 'Scootch là gì và không là gì',
    help: 'Trợ giúp',
    support: 'Hỗ trợ và câu hỏi',
    helplines: 'Đường dây hỗ trợ',
    privacy: 'Quyền riêng tư',
    terms: 'Điều khoản',
    getTheApp: 'Tải app · Android · Báo chí',
    hardTime: 'Đang có chuyện rất khó khăn?',
    hardBody:
      'Bạn xứng đáng có một con người thật lắng nghe. Tìm đường dây hỗ trợ miễn phí, kín đáo ở nước bạn.',
    findHelpline: 'Tìm đường dây hỗ trợ',
    supportTool:
      'Scootch là công cụ hỗ trợ để bắt đầu việc. Scootch không chẩn đoán, điều trị hay chữa ADHD hoặc bất cứ điều gì khác.',
    copyright: '© 2026 Scootch · Làm ra trong cơn hơi hoảng',
    otherLanguage: 'English',
  },
  maker: {
    news: 'Mới',
    newsLine: 'Ngồi chung bàn, thẻ ánh kim, và cuộc săn ngay trên màn hình khoá',
    headline: 'Bạn đang né việc gì vậy?',
    sub: 'Gõ ra đi. Tui biến nó thành một con quái. Rồi mình cùng bắt nó, mỗi lần mười phút. Bạn sẽ thấy nhẹ hơn. Chắc vậy.',
    bubble: 'Nói đi. Tui không phán xét đâu. Chút xíu thôi.',
    typing: [
      'email cho nha sĩ',
      'khai thuế',
      'trả lời tin nhắn của mẹ',
      'cái kệ lung lay',
      'đi tập gym',
      'cái tờ đơn đó',
    ],
    hatchingTitle: 'Có gì đó đang nở…',
    hold: 'Giữ để bắt',
    holding: 'Giữ tiếp…',
    holdIdle: 'Giữ để bắt nó. Trong app, mỗi con quái có một kiểu bắt riêng.',
    holdEarly: 'Bắt đầu là tính rồi. Giữ thêm chút nữa.',
    holdDone: 'Lần bắt nào cũng đã vậy đó.',
    caught: 'Đã bắt',
    onShelf: 'Trên kệ của bạn',
    fieldLabel: 'Cái việc bạn đang né',
    placeholder: 'vd: email cho nha sĩ',
    hatch: 'Ấp nó',
    examplesLabel: 'Ví dụ',
    examples: [
      'khai thuế',
      'email cho nha sĩ',
      'đi tập gym',
      'trả lời tin nhắn của mẹ',
      'cọ nhà tắm',
    ],
    note: 'Không cần đăng ký. Thứ bạn gõ không được giữ lại, trừ khi bạn chia sẻ tấm thẻ.',
    empty: 'Gõ gì cũng được. Một chữ thôi cũng được.',
    nonsense: 'Cái đó là bàn phím hắt xì chứ đâu phải việc. Gõ thử vài chữ nha.',
    hatching: 'Đang ấp… Lắc quả trứng chút. Chừng hai giây.',
    hatchedEyebrow: 'Nở rồi',
    meet: 'Ra mắt {name}.',
    wild: 'Hoang',
    notCaught: 'Chưa ai bắt',
    cardLabel: '{name}. Một con quái hoang. {flavour}',
    showTyped: 'Hiện câu tui đã gõ',
    typedShown: 'Thẻ có ghi “{text}”.',
    typedHidden: 'Đã ẩn. Thẻ chỉ ghi HOANG.',
    catchIt: 'Bắt nó trong app',
    save: 'Lưu thẻ',
    another: 'Ấp con khác',
    napTitle: 'Mười hai con quái rồi. Tui cần nằm một chút.',
    napBody: 'Năm phút nữa lò ấp mở lại. Con mới nhất của bạn vẫn còn đây.',
    napCatch: 'Bắt con mới nhất trong app',
    napOk: 'Ừ, ngủ đi',
    offlineTitle: 'Mất sóng rồi. Lò ấp của tui chạy bằng wifi.',
    offlineBody: 'Tui giữ lại câu bạn gõ rồi. Có mạng lại thì thử lần nữa nha.',
    tryAgain: 'Thử lại',
    seriousTitle: 'Chuyện này nghe nặng nề quá. Mình sẽ không biến nó thành quái đâu.',
    seriousBody: 'Nếu lúc này mọi thứ quá sức, bạn không cần phải gánh một mình.',
    helplineLocal: 'Đang gặp nguy hiểm ngay lúc này? Gọi cấp cứu 115',
    helplineLocalHref: 'tel:115',
    helplineElsewhere: 'Tìm đường dây hỗ trợ ở nước bạn',
    someoneYouTrust: 'Hoặc nói với một người bạn tin. Nhắn cho một người bạn cũng tính.',
    helplineNote:
      'Đường dây hỗ trợ khác nhau tuỳ từng nước. Trang đường dây hỗ trợ có số cho nơi bạn ở.',
    somethingElse: 'Làm con khác',
  },
  strip: {
    label: 'Vài con tui ấp sẵn từ trước',
    monsters: [
      {
        name: 'Thư Chưa Đọc, Kẻ Lì Đòn',
        flavour: '412 thư chưa đọc. Nó bắt đầu đặt tên cho từng cái.',
      },
      { name: 'Rắn Hoá Đơn Chín Đầu', flavour: 'Mất một hoá đơn là mọc thêm một cái đầu.' },
      { name: 'Nam tước Kẽ Gạch', flavour: 'Giờ nhà tắm là của nó. Có đeo kính một mắt.' },
      { name: 'Reng Reng', flavour: 'Reo trong đầu bạn, không reo trong máy.' },
      { name: 'Yêu Tinh Túi Tập', flavour: 'Sống trong túi đồ tập. Thơm mùi quyết tâm.' },
      { name: 'Dương Xỉ Khát Nước', flavour: 'Hay làm quá. Tuần này xỉu hai lần rồi.' },
    ],
  },
  ...homeVi,
} as const satisfies SiteCopy;
